/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : PROXY
 #	author : miyako
 #	2018/01/07
 #
 # --------------------------------------------------------------------------------*/

#include "proxy.h"

// --- PROXY
void GET_PROXIES(sLONG_PTR *pResult, PackagePtr pParams);
